"""
Tests for host-services/utilities scripts.

Tests script functionality including:
- service-failure-notify: Creates notifications for service failures
"""

import tempfile
from datetime import datetime
from pathlib import Path

import pytest


class TestNotificationFileFormat:
    """Tests for notification file format generated by scripts."""

    def test_notification_filename_format(self):
        """Test that notification filename follows expected pattern."""
        timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
        service_name = "slack-notifier"
        expected_pattern = f"{timestamp}-service-failure-{service_name}.md"

        assert expected_pattern.endswith(".md")
        assert "service-failure" in expected_pattern

    def test_notification_content_structure(self, temp_dir):
        """Test the expected structure of notification content."""
        service_name = "test-service"
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        content = f"""# 🚨 Service Failure: {service_name}

**Priority**: High
**Topic**: System Failure
**Time**: {timestamp}

## Service Status

```
● {service_name}.service - Test Service
   Loaded: loaded
   Active: failed
```

## Recent Logs (last 50 lines)

```
Error: Service crashed
```

## Recommended Actions

1. Check logs: `journalctl --user -u {service_name} -f`
2. Restart if needed: `systemctl --user restart {service_name}`

---
📅 {datetime.now()}
🔔 Auto-generated by service-failure-notify
"""

        notif_file = temp_dir / f"service-failure-{service_name}.md"
        notif_file.write_text(content)

        assert notif_file.exists()
        assert "🚨 Service Failure" in notif_file.read_text()
        assert "## Recommended Actions" in notif_file.read_text()


@pytest.fixture
def temp_dir():
    """Create a temporary directory for test files."""
    with tempfile.TemporaryDirectory() as tmpdir:
        yield Path(tmpdir)
