#!/bin/bash
# Notify about systemd service failures via Slack
# Called by service-failure-notify@.service

set -euo pipefail

SERVICE_NAME="$1"
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
NOTIFICATION_FILE="${HOME}/sharing/notifications/$(date +%Y%m%d-%H%M%S)-service-failure-${SERVICE_NAME}.md"

# Get service status info
STATUS_OUTPUT=$(systemctl --user status "$SERVICE_NAME" --no-pager -l 2>&1 || true)
JOURNAL_OUTPUT=$(journalctl --user -u "$SERVICE_NAME" -n 50 --no-pager 2>&1 || true)

# Create notification
cat > "$NOTIFICATION_FILE" <<EOF
# 🚨 Service Failure: ${SERVICE_NAME}

**Priority**: High
**Topic**: System Failure
**Time**: ${TIMESTAMP}

## Service Status

\`\`\`
${STATUS_OUTPUT}
\`\`\`

## Recent Logs (last 50 lines)

\`\`\`
${JOURNAL_OUTPUT}
\`\`\`

## Recommended Actions

1. Check logs: \`journalctl --user -u ${SERVICE_NAME} -f\`
2. Check service status: \`systemctl --user status ${SERVICE_NAME}\`
3. Restart if needed: \`systemctl --user restart ${SERVICE_NAME}\`
4. Check control script: \`~/khan/james-in-a-box/bin/*-ctl status\`

## Context

- **Service**: ${SERVICE_NAME}
- **Host**: $(hostname)
- **Time**: ${TIMESTAMP}
- **Triggered by**: systemd OnFailure directive

---
📅 $(date)
🔔 Auto-generated by service-failure-notify
EOF

# Log the notification
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Created failure notification for ${SERVICE_NAME}" >&2

# The notification file will be picked up by host-notify-slack.py
# which watches ~/sharing/notifications/
