# Hadolint configuration for Dockerfile linting
# See: https://github.com/hadolint/hadolint

# Ignore rules that don't apply to our use case
ignored:
  # DL3008: Pin versions in apt get install
  # We intentionally don't pin to get latest security updates
  - DL3008

  # DL3013: Pin versions in pip
  # Handled separately via requirements.txt
  - DL3013

  # DL3059: Multiple consecutive RUN instructions
  # We optimize for readability over layer count
  - DL3059

# Trusted registries
trustedRegistries:
  - docker.io
  - gcr.io
  - ghcr.io

# Severity overrides
override:
  warning:
    # These are best practices but not critical
    - DL3003  # Use WORKDIR instead of proliferating RUN cd
    - DL3006  # Always tag the version of an image explicitly
    - DL4006  # Set SHELL to use pipefail
