#!/bin/bash
#
# Setup script for LLM Documentation Generator (4-Agent Pipeline)
#
# Installs systemd timer for weekly documentation generation.
# For best practice research, use the separate adr-researcher tool.
#
# Per ADR: LLM Documentation Index Strategy
#
# Usage:
#   ./setup.sh enable        # Enable doc generation timer
#   ./setup.sh disable       # Disable timer
#   ./setup.sh status        # Check timer status
#   ./setup.sh run           # Run doc generation now
#   ./setup.sh run --create-pr  # Run and create a PR for changes
#   ./setup.sh create-pr     # Create PR for existing changes

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
DOC_SERVICE_NAME="jib-doc-generator"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

log_section() {
    echo -e "\n${BLUE}=== $1 ===${NC}"
}

# Create a PR for documentation changes
create_docs_pr() {
    local branch_name="docs/auto-generated-$(date +%Y%m%d-%H%M%S)"
    local docs_dir="${PROJECT_ROOT}/docs/generated"

    log_section "Creating PR for documentation changes"

    # Check if gh CLI is available
    if ! command -v gh &> /dev/null; then
        log_error "GitHub CLI (gh) not found. Install it or create the PR manually."
        log_info "Changes are in: ${docs_dir}"
        return 1
    fi

    # Check if we're in a git repo
    if ! git -C "$PROJECT_ROOT" rev-parse --git-dir &> /dev/null; then
        log_error "Not in a git repository"
        return 1
    fi

    cd "$PROJECT_ROOT"

    # Check for changes in docs/generated
    if ! git diff --quiet -- docs/generated/ 2>/dev/null && \
       ! git diff --cached --quiet -- docs/generated/ 2>/dev/null; then
        log_info "Found changes in docs/generated/"
    elif [ -n "$(git ls-files --others --exclude-standard docs/generated/)" ]; then
        log_info "Found new files in docs/generated/"
    else
        log_info "No documentation changes to commit"
        return 0
    fi

    # Get the default branch
    local default_branch
    default_branch=$(git remote show origin 2>/dev/null | grep 'HEAD branch' | awk '{print $NF}')
    default_branch=${default_branch:-main}

    # Create a new branch from the default branch
    log_info "Creating branch: $branch_name"
    git fetch origin "$default_branch" --quiet
    git checkout -b "$branch_name" "origin/$default_branch"

    # Stage and commit the changes
    git add docs/generated/

    local commit_msg="docs: Auto-generate documentation from codebase analysis

Generated by jib doc-generator 4-agent pipeline:
- Context analysis of code patterns
- Draft generation from indexes
- Review validation
- Output formatting

$(date '+%Y-%m-%d %H:%M:%S')

🤖 Generated with [Claude Code](https://claude.com/claude-code)

Co-Authored-By: Claude <noreply@anthropic.com>"

    git commit -m "$commit_msg"

    # Push the branch
    log_info "Pushing branch to origin..."
    git push -u origin "$branch_name"

    # Create the PR
    log_info "Creating pull request..."

    # Count patterns from generated docs
    local pattern_count=$(find docs/generated/authored -name "*-pattern.md" 2>/dev/null | wc -l)

    local pr_body="## What is This?

This PR contains **auto-generated pattern documentation** created by the 4-agent doc-generator pipeline. The pipeline analyzes the codebase to extract and document architectural patterns.

## What Generated It?

**Generator:** \`host-services/analysis/doc-generator/doc-generator.py\`

**4-Agent Pipeline:**
1. **Context Agent** - Analyzes codebase indexes (patterns.json, codebase.json) to gather pattern information
2. **Draft Agent** - Generates initial documentation from extracted patterns
3. **Review Agent** - Validates accuracy, checks for empty sections and broken references
4. **Output Agent** - Formats and saves the final documentation

**Trigger:** Scheduled systemd timer (weekly) or manual execution via \`bin/generate-docs --all\`

## Why Does This Exist?

**Problem:** LLM agents (like jib) need to understand project-specific patterns to work effectively, but:
- Dumping all documentation into context is inefficient
- Manually maintaining pattern docs is burdensome
- Pattern documentation drifts as code evolves

**Solution:** Auto-generated pattern documentation that:
- Extracts patterns directly from code analysis (via codebase analyzer)
- Provides concise, navigable references for LLMs
- Stays current through automated regeneration
- Supports drift detection to catch stale references

**Architecture Decision:** See [ADR: LLM Documentation Index Strategy](../docs/adr/implemented/ADR-LLM-Documentation-Index-Strategy.md)

## What Are These Docs Used For?

These generated docs serve as **reference material for LLM agents** (including jib itself):

1. **Pattern Reference**: Quick lookup of how specific patterns (config, connector, sync, etc.) are implemented
2. **Status Quo Documentation**: Describes \"how we currently do things\" with code examples and conventions
3. **Navigation Aid**: Links to existing related documentation
4. **Drift Detection Input**: Checked by \`bin/check-doc-drift\` to find stale references

**Target Audience:** LLM agents (primary), human developers (secondary for pattern discovery)

## What Changed

Generated documentation for ${pattern_count} detected patterns.

Each pattern has 2 doc types:
- \`{pattern}-pattern.md\`: Concise pattern overview
- \`{pattern}-patterns-status-quo.md\`: Detailed current implementation with components table

**File changes:**
\`\`\`
$(git diff --stat "origin/$default_branch"...HEAD -- docs/generated/ | head -20)
\`\`\`

**Also includes:** Minor code formatting fixes from ruff/black auto-formatting (if any)

## How to Review

1. **Accuracy**: Do the extracted patterns accurately reflect the codebase?
2. **Usefulness**: Are the code examples and conventions helpful?
3. **Completeness**: Are any major patterns missing?
4. **Drift**: Run \`bin/check-doc-drift\` to verify all file references are valid

## Test Plan

- [x] Generated docs are syntactically valid markdown
- [x] File references point to existing files (checked by review agent)
- [ ] **Human review**: Pattern descriptions accurately reflect codebase
- [ ] **Human review**: Conventions match actual development practices
- [ ] Run drift detector: \`bin/check-doc-drift\`

---

🤖 Generated with [Claude Code](https://claude.com/claude-code)

— Authored by jib"

    local pr_url
    pr_url=$(gh pr create \
        --title "docs: Auto-generated documentation from 4-agent pipeline" \
        --body "$pr_body" \
        --base "$default_branch" \
        --head "$branch_name" 2>&1)

    if [ $? -eq 0 ]; then
        log_info "PR created: $pr_url"
        echo ""
        echo "$pr_url"
        return 0
    else
        log_error "Failed to create PR: $pr_url"
        log_info "Branch pushed. Create PR manually at: https://github.com/$(git remote get-url origin | sed 's/.*github.com[:/]\(.*\)\.git/\1/')/pull/new/$branch_name"
        return 1
    fi
}

# Check if running as user with systemd access
check_systemd() {
    if ! command -v systemctl &> /dev/null; then
        log_error "systemctl not found. This script requires systemd."
        exit 1
    fi
}

# Create systemd service for doc generation
create_doc_service() {
    local service_file="$HOME/.config/systemd/user/${DOC_SERVICE_NAME}.service"
    mkdir -p "$(dirname "$service_file")"

    cat > "$service_file" << EOF
[Unit]
Description=JIB Documentation Generator (4-Agent Pipeline)
After=network.target

[Service]
Type=oneshot
WorkingDirectory=${PROJECT_ROOT}
ExecStart=/bin/bash -c 'python3 ${SCRIPT_DIR}/doc-generator.py --all --type status-quo && (python3 ${SCRIPT_DIR}/drift-detector.py --suggest-fixes || true) && ${SCRIPT_DIR}/setup.sh create-pr'
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=default.target
EOF

    log_info "Created doc service: $service_file"
}

# Create systemd timer for weekly doc generation
create_doc_timer() {
    local timer_file="$HOME/.config/systemd/user/${DOC_SERVICE_NAME}.timer"
    mkdir -p "$(dirname "$timer_file")"

    cat > "$timer_file" << EOF
[Unit]
Description=Weekly JIB Documentation Generation

[Timer]
# Run weekly on Monday at 11am
OnCalendar=Mon *-*-* 11:00:00
# If system was off when timer should have run, run it on next boot
Persistent=true
# Randomize start time to avoid resource spikes
RandomizedDelaySec=300

[Install]
WantedBy=timers.target
EOF

    log_info "Created doc timer: $timer_file"
}

enable_timer() {
    check_systemd

    log_section "Setting up documentation generator timer"

    create_doc_service
    create_doc_timer

    systemctl --user daemon-reload
    systemctl --user enable "${DOC_SERVICE_NAME}.timer"
    systemctl --user start "${DOC_SERVICE_NAME}.timer"

    log_info "Doc generation timer enabled (weekly on Mondays at 11am)"
    log_info "Run 'systemctl --user list-timers' to see scheduled runs"
}

disable_timer() {
    check_systemd

    log_info "Disabling timer..."

    systemctl --user stop "${DOC_SERVICE_NAME}.timer" 2>/dev/null || true
    systemctl --user disable "${DOC_SERVICE_NAME}.timer" 2>/dev/null || true

    log_info "Timer disabled."
}

show_status() {
    check_systemd

    log_section "Documentation Generator Timer"
    systemctl --user status "${DOC_SERVICE_NAME}.timer" 2>/dev/null || log_warn "Timer not installed"

    log_section "Scheduled Runs"
    systemctl --user list-timers "${DOC_SERVICE_NAME}.timer" 2>/dev/null || log_warn "No timers scheduled"
}

run_now() {
    local create_pr="${1:-false}"

    log_section "Running documentation generation pipeline"

    cd "$PROJECT_ROOT"

    echo ""
    log_info "Step 1: Generating documentation from codebase indexes..."
    python3 "${SCRIPT_DIR}/doc-generator.py" --all --type status-quo

    echo ""
    log_info "Step 2: Checking for documentation drift..."
    python3 "${SCRIPT_DIR}/drift-detector.py" --suggest-fixes || true

    if [ "$create_pr" = "true" ]; then
        echo ""
        log_info "Step 3: Creating PR for changes..."
        create_docs_pr
    else
        log_info "Done. Run with --create-pr to create a PR for the changes."
    fi
}

show_help() {
    cat << EOF
JIB Documentation Generator Setup (4-Agent Pipeline)

Usage: $0 <command> [options]

Commands:
  enable           Enable documentation generation timer
  disable          Disable timer
  status           Show timer status
  run              Run doc generation now
  run --create-pr  Run and create a GitHub PR for changes
  create-pr        Create a PR for existing doc changes (without regenerating)

  help             Show this help message

Schedule:
  Doc Generation:  Mondays at 11:00am
                   Automatically creates a PR if changes are detected

The 4-agent pipeline:
  1. Context Agent  - Analyzes code patterns from indexes
  2. Draft Agent    - Generates initial documentation
  3. Review Agent   - Validates accuracy and completeness
  4. Output Agent   - Formats and saves documentation

Note: For best practice research, use the adr-researcher tool instead.

Requirements for PR creation:
  - GitHub CLI (gh) must be installed and authenticated
  - Repository must be a git repo with an 'origin' remote
EOF
}

# Main
# Default to 'enable' when called without arguments (for integration with root setup.sh)
case "${1:-enable}" in
    enable)
        enable_timer
        ;;
    disable)
        disable_timer
        ;;
    status)
        show_status
        ;;
    run)
        if [ "${2:-}" = "--create-pr" ]; then
            run_now true
        else
            run_now false
        fi
        ;;
    create-pr)
        create_docs_pr
        ;;
    help|--help|-h)
        show_help
        ;;
    *)
        log_error "Unknown command: $1"
        show_help
        exit 1
        ;;
esac
