"""Network mode configuration for jib.

This module manages the network mode setting that controls:
- Whether all network traffic is allowed (ALLOW_ALL_NETWORK)
- Whether only private repos are accessible (PRIVATE_REPO_MODE)
- Whether only public repos are accessible (PUBLIC_REPO_ONLY_MODE)

The network mode is stored in ~/.config/jib/network-mode and read by
the gateway sidecar at startup.

Security invariant:
- ALLOW_ALL_NETWORK=true requires PUBLIC_REPO_ONLY_MODE=true
  (Open network access means only public repos to prevent data exfiltration)
"""

import subprocess
from enum import Enum

from .config import Config
from .output import error, info, warn


class NetworkMode(Enum):
    """Network mode options for jib.

    DEFAULT: Network lockdown, all repos accessible (private + public)
    ALLOW_ALL: All network traffic allowed, only public repos accessible
    PRIVATE_ONLY: Network lockdown, only private repos accessible
    """

    DEFAULT = "default"
    ALLOW_ALL = "allow-all"
    PRIVATE_ONLY = "private-only"


# Config file for network mode
NETWORK_MODE_FILE = Config.USER_CONFIG_DIR / "network-mode"


def get_network_mode() -> NetworkMode:
    """Get the current network mode setting.

    Returns:
        The configured NetworkMode, defaults to DEFAULT if not set.
    """
    if not NETWORK_MODE_FILE.exists():
        return NetworkMode.DEFAULT

    try:
        mode_str = NETWORK_MODE_FILE.read_text().strip()
        return NetworkMode(mode_str)
    except (ValueError, OSError):
        return NetworkMode.DEFAULT


def set_network_mode(mode: NetworkMode) -> bool:
    """Set the network mode.

    Args:
        mode: The network mode to set.

    Returns:
        True if successful, False otherwise.
    """
    try:
        NETWORK_MODE_FILE.parent.mkdir(parents=True, exist_ok=True)
        NETWORK_MODE_FILE.write_text(mode.value)
        return True
    except OSError as e:
        error(f"Failed to write network mode: {e}")
        return False


def get_network_mode_env_vars(mode: NetworkMode) -> dict[str, str]:
    """Get environment variables for the given network mode.

    Args:
        mode: The network mode.

    Returns:
        Dict of environment variable names to values.
    """
    if mode == NetworkMode.ALLOW_ALL:
        # Open network + public repos only
        return {
            "ALLOW_ALL_NETWORK": "true",
            "PUBLIC_REPO_ONLY_MODE": "true",
            "PRIVATE_REPO_MODE": "false",
        }
    elif mode == NetworkMode.PRIVATE_ONLY:
        # Network lockdown + private repos only
        return {
            "ALLOW_ALL_NETWORK": "false",
            "PUBLIC_REPO_ONLY_MODE": "false",
            "PRIVATE_REPO_MODE": "true",
        }
    else:
        # Default: network lockdown + all repos
        return {
            "ALLOW_ALL_NETWORK": "false",
            "PUBLIC_REPO_ONLY_MODE": "false",
            "PRIVATE_REPO_MODE": "false",
        }


def write_network_env_file() -> bool:
    """Write the network mode environment variables to a file.

    The gateway sidecar sources this file at startup.

    Returns:
        True if successful, False otherwise.
    """
    mode = get_network_mode()
    env_vars = get_network_mode_env_vars(mode)

    env_file = Config.USER_CONFIG_DIR / "network.env"
    try:
        env_file.parent.mkdir(parents=True, exist_ok=True)
        lines = [f"# Auto-generated by jib - network mode: {mode.value}"]
        for key, value in env_vars.items():
            lines.append(f"{key}={value}")
        env_file.write_text("\n".join(lines) + "\n")
        return True
    except OSError as e:
        error(f"Failed to write network env file: {e}")
        return False


def restart_gateway_if_mode_changed(quiet: bool = False) -> bool:
    """Restart the gateway service if network mode has changed.

    This writes the current mode to the env file and restarts the
    gateway-sidecar systemd service.

    Args:
        quiet: Suppress output messages.

    Returns:
        True if gateway restarted successfully, False otherwise.
    """
    # Write the network env file
    if not write_network_env_file():
        return False

    if not quiet:
        info("Restarting gateway with new network mode...")

    # Restart the gateway sidecar service
    result = subprocess.run(
        ["systemctl", "--user", "restart", "gateway-sidecar.service"],
        capture_output=True,
        text=True,
        check=False,
    )

    if result.returncode != 0:
        # Service might not be installed, try direct docker restart
        docker_result = subprocess.run(
            ["docker", "restart", "jib-gateway"],
            capture_output=True,
            text=True,
            check=False,
        )
        if docker_result.returncode != 0:
            if not quiet:
                warn("Gateway not running - will start with new mode on next run")
            return True  # Not a failure, gateway will start with new mode

    if not quiet:
        mode = get_network_mode()
        if mode == NetworkMode.ALLOW_ALL:
            info("Network mode: ALLOW ALL (web search enabled, PUBLIC repos only)")
        elif mode == NetworkMode.PRIVATE_ONLY:
            info("Network mode: PRIVATE REPOS ONLY (network lockdown)")
        else:
            info("Network mode: DEFAULT (network lockdown, all repos)")

    return True
