# GitHub Actions workflow template for feature documentation drift detection
#
# This workflow checks that documented features reference valid file paths
# and warns when feature documentation may be stale.
#
# Install: Copy to .github/workflows/check-feature-docs.yml
#
# Per ADR: Jib Repository Onboarding Strategy

name: Check Feature Documentation

on:
  push:
    branches: [main, master]
    paths:
      - '**/*.py'
      - '**/*.ts'
      - '**/*.js'
      - '**/*.go'
      - 'docs/FEATURES.md'
      - 'docs/features/**'
  pull_request:
    branches: [main, master]
    paths:
      - '**/*.py'
      - '**/*.ts'
      - '**/*.js'
      - '**/*.go'
      - 'docs/FEATURES.md'
      - 'docs/features/**'

jobs:
  check-feature-docs:
    name: Verify Feature Documentation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check FEATURES.md exists
        id: check-features
        run: |
          if [ -f "docs/FEATURES.md" ]; then
            echo "has_features=true" >> "$GITHUB_OUTPUT"
          else
            echo "has_features=false" >> "$GITHUB_OUTPUT"
            echo "::notice::No docs/FEATURES.md found - skipping feature doc checks"
          fi

      - name: Check for documentation drift
        if: steps.check-features.outputs.has_features == 'true'
        run: |
          echo "Checking that documented features reference existing code..."

          DRIFT_FOUND=false
          CHECKED=0
          MISSING=0

          # Extract file paths from FEATURES.md (formats: `path/file.ext` or path/file.ext)
          # Support Python, TypeScript, JavaScript, Go files
          grep -oP '`[^`]+\.(py|ts|js|go|tsx|jsx)`' docs/FEATURES.md 2>/dev/null | tr -d '`' | sort -u | while read -r path; do
            CHECKED=$((CHECKED + 1))
            if [ ! -f "$path" ]; then
              echo "::warning file=docs/FEATURES.md::Documentation drift: $path referenced but doesn't exist"
              DRIFT_FOUND=true
              MISSING=$((MISSING + 1))
            fi
          done

          # Also check backtick-free paths that look like file references
          grep -oP '(?<![`\w])[a-zA-Z0-9_/-]+\.(py|ts|js|go|tsx|jsx)(?![`\w])' docs/FEATURES.md 2>/dev/null | sort -u | while read -r path; do
            # Skip if it's clearly not a file path (e.g., contains http)
            if [[ "$path" != *"http"* ]] && [[ "$path" != *".d.ts"* ]]; then
              if [ ! -f "$path" ] && [ ! -f "src/$path" ]; then
                echo "::notice file=docs/FEATURES.md::Possible stale reference: $path"
              fi
            fi
          done

          echo "Feature documentation paths checked."

      - name: Check feature docs directory
        if: steps.check-features.outputs.has_features == 'true'
        run: |
          if [ -d "docs/features" ]; then
            echo "Checking docs/features/ for broken links..."

            for doc in docs/features/*.md; do
              if [ -f "$doc" ]; then
                # Check markdown links
                grep -oP '\[.*?\]\(((?!http)[^)]+)\)' "$doc" 2>/dev/null | grep -oP '\(([^)]+)\)' | tr -d '()' | while read -r link; do
                  # Resolve relative path from doc location
                  target="$(dirname "$doc")/$link"
                  target="$(realpath --relative-to=. "$target" 2>/dev/null || echo "$target")"
                  if [[ "$link" != "#"* ]] && [ ! -e "$target" ]; then
                    echo "::warning file=$doc::Broken link in $doc: $link"
                  fi
                done
              fi
            done
          fi

          echo "Feature docs directory checked."

      - name: Summary
        if: always()
        run: |
          echo "## Feature Documentation Check Complete"
          echo ""
          echo "If you see drift warnings, consider running:"
          echo "  feature-analyzer full-repo --repo-root ."
          echo ""
          echo "To regenerate feature documentation."
