#!/usr/bin/env python3
"""
Rollback Utilities for Auto-Generated Documentation (Phase 4)

This module provides tools for finding and reverting auto-generated
documentation updates. It implements the rollback strategy defined
in ADR-Feature-Analyzer-Documentation-Sync.

Traceability mechanisms used:
1. Commit message convention: "docs: Sync with [ADR-filename] (auto-generated)"
2. HTML metadata in docs: <!-- Auto-updated from ADR-XYZ on YYYY-MM-DD -->
3. Git tags: auto-doc-sync-YYYYMMDD

Usage:
    rollback = Rollback(repo_root)
    commits = rollback.find_auto_generated_commits(since="1 week ago")
    rollback.show_auto_generated_files()
    rollback.revert_doc(path, commit_sha)
"""

import subprocess
from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class AutoGeneratedCommit:
    """Represents a commit with auto-generated documentation."""

    sha: str
    message: str
    date: str
    adr_filename: str | None = None
    files: list[str] = field(default_factory=list)


@dataclass
class RollbackResult:
    """Result of a rollback operation."""

    success: bool
    message: str
    sha: str | None = None
    reverted_files: list[str] = field(default_factory=list)


class Rollback:
    """Utilities for finding and reverting auto-generated documentation."""

    def __init__(self, repo_root: Path):
        """
        Initialize rollback utilities.

        Args:
            repo_root: Path to the repository root
        """
        self.repo_root = repo_root

    def _run_git(self, *args: str, check: bool = True) -> subprocess.CompletedProcess:
        """Run a git command in the repo root."""
        return subprocess.run(
            ["git", *args],
            cwd=self.repo_root,
            capture_output=True,
            text=True,
            check=check,
        )

    def find_auto_generated_commits(
        self, since: str | None = None, adr_filename: str | None = None
    ) -> list[AutoGeneratedCommit]:
        """
        Find commits containing auto-generated documentation.

        Args:
            since: Git date filter (e.g., "1 week ago", "2025-01-01")
            adr_filename: Optional ADR filename to filter by

        Returns:
            List of AutoGeneratedCommit objects
        """
        # Build git log command
        cmd = ["log", "--grep=auto-generated", "--oneline"]

        if since:
            cmd.append(f"--since={since}")

        if adr_filename:
            cmd.append(f"--grep={adr_filename}")

        result = self._run_git(*cmd, check=False)

        if not result.stdout.strip():
            return []

        commits = []
        for line in result.stdout.strip().split("\n"):
            if not line:
                continue

            parts = line.split(" ", 1)
            sha = parts[0]
            parts[1] if len(parts) > 1 else ""

            # Get commit details
            commit = self._get_commit_details(sha)
            if commit:
                commits.append(commit)

        return commits

    def _get_commit_details(self, sha: str) -> AutoGeneratedCommit | None:
        """Get detailed information about a commit."""
        try:
            # Get commit message
            msg_result = self._run_git("log", "-1", "--format=%B", sha)
            message = msg_result.stdout.strip()

            # Get commit date
            date_result = self._run_git("log", "-1", "--format=%ci", sha)
            date = date_result.stdout.strip()

            # Get changed files
            files_result = self._run_git("show", "--name-only", "--format=", sha)
            files = [f for f in files_result.stdout.strip().split("\n") if f]

            # Extract ADR filename from commit message
            adr_filename = None
            if "Sync with " in message:
                # Extract ADR name from "Sync with ADR-XYZ"
                import re

                match = re.search(r"Sync with (ADR-[^\s(]+)", message)
                if match:
                    adr_filename = match.group(1)

            return AutoGeneratedCommit(
                sha=sha,
                message=message.split("\n")[0],  # First line only
                date=date,
                adr_filename=adr_filename,
                files=files,
            )
        except subprocess.CalledProcessError:
            return None

    def find_auto_generated_tags(self) -> list[str]:
        """
        Find all auto-doc-sync tags.

        Returns:
            List of tag names
        """
        result = self._run_git("tag", "-l", "auto-doc-sync-*", check=False)
        if not result.stdout.strip():
            return []
        return result.stdout.strip().split("\n")

    def find_files_with_metadata(self) -> list[tuple[Path, str]]:
        """
        Find documentation files with auto-generated metadata comments.

        Returns:
            List of (file_path, adr_reference) tuples
        """
        result = self._run_git(
            "grep", "-l", "Auto-updated from", "--", "docs/", "*.md", check=False
        )

        if not result.stdout.strip():
            return []

        files_with_metadata = []
        for file_path in result.stdout.strip().split("\n"):
            if not file_path:
                continue

            full_path = self.repo_root / file_path

            # Extract ADR reference from metadata comment
            try:
                content = full_path.read_text()
                import re

                match = re.search(
                    r"<!-- Auto-updated from (ADR-[^\s]+) on (\d{4}-\d{2}-\d{2}) -->",
                    content,
                )
                if match:
                    adr_ref = f"{match.group(1)} on {match.group(2)}"
                    files_with_metadata.append((full_path, adr_ref))
            except Exception:
                pass

        return files_with_metadata

    def revert_single_file(
        self, file_path: Path, target_commit: str | None = None
    ) -> RollbackResult:
        """
        Revert a single documentation file.

        Args:
            file_path: Path to the file to revert
            target_commit: Commit to revert to. If None, reverts to before
                          last auto-generated change.

        Returns:
            RollbackResult
        """
        relative_path = file_path.relative_to(self.repo_root)

        try:
            if target_commit is None:
                # Find the last auto-generated commit for this file
                result = self._run_git(
                    "log",
                    "--grep=auto-generated",
                    "--oneline",
                    "-1",
                    "--",
                    str(relative_path),
                )

                if not result.stdout.strip():
                    return RollbackResult(
                        success=False,
                        message=f"No auto-generated commits found for {relative_path}",
                    )

                auto_commit = result.stdout.strip().split()[0]
                # Get the commit before the auto-generated one
                target_commit = f"{auto_commit}~1"

            # Checkout the file from target commit
            self._run_git("checkout", target_commit, "--", str(relative_path))

            return RollbackResult(
                success=True,
                message=f"Reverted {relative_path} to {target_commit}",
                sha=target_commit,
                reverted_files=[str(relative_path)],
            )

        except subprocess.CalledProcessError as e:
            return RollbackResult(
                success=False,
                message=f"Failed to revert {relative_path}: {e.stderr}",
            )

    def revert_adr_batch(self, adr_filename: str) -> RollbackResult:
        """
        Revert all changes from a specific ADR.

        Args:
            adr_filename: ADR filename (e.g., "ADR-Feature-Analyzer")

        Returns:
            RollbackResult
        """
        # Find commits for this ADR
        commits = self.find_auto_generated_commits(adr_filename=adr_filename)

        if not commits:
            return RollbackResult(
                success=False,
                message=f"No auto-generated commits found for {adr_filename}",
            )

        # Get all files from these commits
        all_files = set()
        for commit in commits:
            all_files.update(commit.files)

        reverted_files = []
        errors = []

        for file_path in all_files:
            full_path = self.repo_root / file_path
            if full_path.exists():
                result = self.revert_single_file(full_path)
                if result.success:
                    reverted_files.extend(result.reverted_files)
                else:
                    errors.append(result.message)

        if errors:
            return RollbackResult(
                success=len(reverted_files) > 0,
                message=f"Partially reverted. Errors: {'; '.join(errors)}",
                reverted_files=reverted_files,
            )

        return RollbackResult(
            success=True,
            message=f"Reverted {len(reverted_files)} file(s) from {adr_filename}",
            reverted_files=reverted_files,
        )


def main():
    """CLI interface for rollback utilities."""
    import argparse

    parser = argparse.ArgumentParser(
        description="Rollback utilities for auto-generated documentation"
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=Path.cwd(),
        help="Repository root directory",
    )

    subparsers = parser.add_subparsers(dest="command", required=True)

    # list-commits command
    list_parser = subparsers.add_parser("list-commits", help="List auto-generated commits")
    list_parser.add_argument("--since", help="Show commits since date (e.g., '1 week ago')")
    list_parser.add_argument("--adr", help="Filter by ADR filename")

    # list-files command
    subparsers.add_parser("list-files", help="List files with auto-generated metadata")

    # list-tags command
    subparsers.add_parser("list-tags", help="List auto-doc-sync tags")

    # revert-file command
    revert_file_parser = subparsers.add_parser("revert-file", help="Revert a single file")
    revert_file_parser.add_argument("file", type=Path, help="Path to file to revert")
    revert_file_parser.add_argument(
        "--to", help="Commit to revert to (default: before last auto-generated)"
    )

    # revert-adr command
    revert_adr_parser = subparsers.add_parser("revert-adr", help="Revert all changes from an ADR")
    revert_adr_parser.add_argument("adr", help="ADR filename (e.g., ADR-Feature-Analyzer)")

    args = parser.parse_args()

    rollback = Rollback(args.repo_root)

    if args.command == "list-commits":
        commits = rollback.find_auto_generated_commits(since=args.since, adr_filename=args.adr)

        if not commits:
            print("No auto-generated commits found.")
            return

        print(f"Found {len(commits)} auto-generated commit(s):\n")
        for commit in commits:
            print(f"  {commit.sha[:8]} - {commit.message}")
            print(f"    Date: {commit.date}")
            if commit.adr_filename:
                print(f"    ADR: {commit.adr_filename}")
            if commit.files:
                print(f"    Files: {', '.join(commit.files[:3])}")
                if len(commit.files) > 3:
                    print(f"           ... and {len(commit.files) - 3} more")
            print()

    elif args.command == "list-files":
        files = rollback.find_files_with_metadata()

        if not files:
            print("No files with auto-generated metadata found.")
            return

        print(f"Found {len(files)} file(s) with auto-generated metadata:\n")
        for file_path, adr_ref in files:
            rel_path = file_path.relative_to(args.repo_root)
            print(f"  {rel_path}")
            print(f"    Updated from: {adr_ref}")
            print()

    elif args.command == "list-tags":
        tags = rollback.find_auto_generated_tags()

        if not tags:
            print("No auto-doc-sync tags found.")
            return

        print(f"Found {len(tags)} auto-doc-sync tag(s):\n")
        for tag in tags:
            print(f"  {tag}")

    elif args.command == "revert-file":
        result = rollback.revert_single_file(args.file, target_commit=args.to)

        if result.success:
            print(f"✓ {result.message}")
            print("\nNote: Changes are staged but not committed.")
            print("Review and commit with: git commit -m 'Revert auto-generated changes'")
        else:
            print(f"✗ {result.message}")

    elif args.command == "revert-adr":
        result = rollback.revert_adr_batch(args.adr)

        if result.success:
            print(f"✓ {result.message}")
            if result.reverted_files:
                print("\nReverted files:")
                for f in result.reverted_files:
                    print(f"  - {f}")
            print("\nNote: Changes are staged but not committed.")
            print("Review and commit with: git commit -m 'Revert auto-generated changes'")
        else:
            print(f"✗ {result.message}")


if __name__ == "__main__":
    main()
