#!/usr/bin/env python3
"""
Setup script for Confluence documentation sync.
"""

import os
import sys
from pathlib import Path


def get_user_input(prompt: str, default: str = "") -> str:
    """Get user input with optional default value."""
    if default:
        user_input = input(f"{prompt} [{default}]: ").strip()
        return user_input if user_input else default
    else:
        return input(f"{prompt}: ").strip()


def create_env_file():
    """Create a .env file with Confluence configuration."""
    print("Confluence Documentation Sync Setup")
    print("=" * 40)
    print()

    # Get Confluence instance details
    base_url = get_user_input(
        "Enter your Confluence instance URL", "https://khanacademy.atlassian.net/wiki"
    )

    username = get_user_input("Enter your Confluence username (email)", "your.email@company.com")

    api_token = get_user_input("Enter your Confluence API token", "")

    if not api_token:
        print("\nTo get your API token:")
        print("1. Go to https://id.atlassian.com/manage-profile/security/api-tokens")
        print("2. Click 'Create API token'")
        print("3. Give it a name like 'Documentation Sync'")
        print("4. Copy the token and paste it here")
        print()
        api_token = get_user_input("Enter your Confluence API token")

    space_keys = get_user_input("Enter space keys to sync (comma-separated)", "TEAM,DEV,ARCH")

    output_format = get_user_input("Choose output format (html/markdown)", "html").lower()

    # Validate output format
    if output_format not in ["html", "markdown"]:
        print(f"Warning: '{output_format}' is not a valid format. Defaulting to 'html'")
        output_format = "html"

    # Create .env file
    env_content = f"""# Confluence Documentation Sync Configuration
# Generated by setup.py

CONFLUENCE_BASE_URL={base_url}
CONFLUENCE_USERNAME={username}
CONFLUENCE_API_TOKEN={api_token}
CONFLUENCE_SPACE_KEYS={space_keys}

# Optional settings
CONFLUENCE_MAX_PAGES=100
CONFLUENCE_INCLUDE_ATTACHMENTS=false
CONFLUENCE_OUTPUT_FORMAT={output_format}
"""

    env_file = Path(".env")
    if env_file.exists():
        overwrite = input("\n.env file already exists. Overwrite? (y/N): ").strip().lower()
        if overwrite != "y":
            print("Setup cancelled.")
            return

    with open(env_file, "w") as f:
        f.write(env_content)

    print(f"\nConfiguration saved to {env_file}")
    print("\nNext steps:")
    print("1. Review the configuration in .env")
    print("2. Run: make docs-sync")
    print('3. Search documentation with: make docs-search QUERY="your search term"')


def test_connection():
    """Test the Confluence connection."""
    print("Testing Confluence connection...")

    # Load environment variables
    from dotenv import load_dotenv

    load_dotenv()

    base_url = os.getenv("CONFLUENCE_BASE_URL")
    username = os.getenv("CONFLUENCE_USERNAME")
    api_token = os.getenv("CONFLUENCE_API_TOKEN")
    space_keys = os.getenv("CONFLUENCE_SPACE_KEYS")

    if not all([base_url, username, api_token, space_keys]):
        print("Error: Missing required environment variables.")
        print("Run this script first to set up configuration.")
        return False

    try:
        from connectors.confluence.sync import ConfluenceSync

        syncer = ConfluenceSync()

        # Test with first space
        space_key = space_keys.split(",")[0].strip()
        print(f"Testing connection to space: {space_key}")

        pages = syncer.get_pages_in_space(space_key)
        print(f"Success! Found {len(pages)} pages in space {space_key}")

        if pages:
            print("Sample pages:")
            for page in pages[:3]:
                print(f"  - {page['title']}")

        return True

    except Exception as e:
        print(f"Connection failed: {e}")
        print("\nPlease check:")
        print("1. Your Confluence URL is correct")
        print("2. Your username and API token are correct")
        print("3. You have access to the specified spaces")
        return False


def main():
    """Main setup function."""
    if len(sys.argv) > 1 and sys.argv[1] == "test":
        test_connection()
    else:
        create_env_file()


if __name__ == "__main__":
    main()
